import React from 'react';
import { openInNewTab } from '../../pages';
import { CTADivider } from './dividers/CTADivider';

export const CTAComponent = () => {
  const handleReadDocumentationClick = () => {
    openInNewTab('https://docs.credix.finance/')
  }

  return (
    <div className="h-flex-column cta-component-investors">
      <div className="h-flex-row h-flex-row--space-between cta-component-investors--row">
        <div className="h-flex-column cta-component-investors--column">
          <div className="h-flex-column cta-component-investors--column--row-mobile">
            <span className="cta-component-investors--sub-title">Enhance Yield</span>
            <CTADivider/>
            <span className="cta-component-investors--text">Access sustainable returns generated by cash flows of real-world assets.</span>
          </div>
        </div>
        <div className="h-flex-column cta-component-investors--column">
          <div className="h-flex-column cta-component-investors--column--row-mobile">
            <span className="cta-component-investors--sub-title">Diversify Risk</span>
            <CTADivider/>
            <span className="cta-component-investors--text">We provide low sensitivity to equity and crypto markets.</span>
          </div>
        </div>
        <div className="h-flex-column cta-component-investors--column">
          <div className="h-flex-column cta-component-investors--column--row-mobile">
            <span className="cta-component-investors--sub-title">Scalable Ecosystem</span>
            <CTADivider/>
            <span className="cta-component-investors--text">Via the Credix platform, you can access investments via a digital-first platform.</span>
          </div>
        </div>
      </div>
      <div className="h-flex-column cta-component--investors">
        <div className="h-flex-row h-flex-row--space-between cta-component-investors--row">
          <div className="h-flex-column cta-component-investors--column">
            <div className="h-flex-column cta-component-investors--column--row-mobile">
              <span
                className="cta-component-investors--text--cta-link" onClick={handleReadDocumentationClick}>Read our documentation -{'>'}</span>
            </div>
          </div>
          <div className="h-flex-column cta-component-investors--column"/>
          <div className="h-flex-column cta-component-investors--column"/>
        </div>
      </div>
    </div>
  );
}







